esphome:
  name: mhi-room_name
  platform: ESP8266
  board: d1_mini
  includes:
    - mhi_ac_ctrl.h
    - MHI-AC-Ctrl-core.h
    - MHI-AC-Ctrl-core.cpp

wifi:
  ssid: "**SSID**"
  password: "**PASSWORD**"

logger:
  level: DEBUG
  baud_rate: 0

api:
  reboot_timeout: 5min

ota:
  password: ""

climate:
  - platform: custom
    lambda: |-
      auto mhi_ac_ctrl = new MhiAcCtrl();
      App.register_component(mhi_ac_ctrl);
      return {mhi_ac_ctrl};

    climates:
      - name: "MHI-AC-Ctrl-room_name"
        id: mhi_room_name

sensor:
  - platform: custom
    lambda: |-
      return ((MhiAcCtrl*)mhi_ac_ctrl)->get_sensors();

    sensors:
      - name: "Error code"
      - name: "Outdoor temperature"
      - name: "Compressor frequency"
      - name: "Current"
      - name: "Indoor fan speed"
      - name: "Outdoor fan speed"

binary_sensor:
  - platform: custom
    lambda: |-
      return ((MhiAcCtrl*)mhi_ac_ctrl)->get_binary_sensors();

    binary_sensors:
      - name: "Defrost"
